### ISSUE TITLE
How to access IB gateway from Linux

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#10]
Where do you run your IB Gateway or TWS?  

I'm using wsl2 and run IB Gateway on my windows 10, I have difficulty trying to connect to it from wsl2 (linux), It keeps on saying connection failed.

Thanks.

**Comment by psemdel** [comment]
Can you give more detail? I use TWS in Linux personally. For the connection, I completely rely on ib_insync.

**Comment by ben1628** [comment]
Oh, Ic, you are running TWS in Linux. I'll figure it out myself, thanks.

**Comment by psemdel** [comment]
Good notice though, I always used TWS and don't know well IB Gateway. To deploy the bot on "production", IB Gateway could be an idea. ib_sync supports both anyhow. One more point in my backlog.

**Comment by ben1628** [comment]
I know both quite well, and actually have been using it with C# with lots of success.  However, I am now into python, vectorbt pro.  Because of your project, I'm going to linux which I haven't been using it for quite a while, but I actually love it.

Lots to learn, but it's fun.

**Comment by ben1628** [comment]
Ok, I have found the solution.

After google this for a while and try multiple solutions, this is the solution that seem to work

https://learn.microsoft.com/en-us/windows/wsl/networking

So basically:

Step 1:

Obtain the IP address of your host machine by running this command from your Linux distribution: cat /etc/resolv.conf
Copy the IP address following the term: nameserver.
Connect to any Windows server using the copied IP address.

and then you just use that IP Address for

ib.connect('xxx.xxx.x.x', 7497, clientId=1)

Step 2:

In wsl2 terminal, run ip route, that will give you two addresses, one from default via, and the other after scope link src. Both have to be put in the IB API setting under trusted IP

**Comment by psemdel** [comment]
I am not as fast as you, but I will definitely try it. IB gateway is actually the right software (not TWS) for our purpose.
