### ISSUE TITLE
Nasdaq/NYSE trading

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#12]
For those of us that are trading in Nasdaq/NYSE, how do we go about setting this up, as I am not familiar with European markets.

Minimal version may be a good place to put it, with some simple explanation.

btw, thanks for the constant update

**Comment by psemdel** [comment]
There is nothing special to do for Nasdaq/Nyse. You should list the stocks ("action" in French, I should rename some day) you want to trade with the right ticker. Define the corresponding stock exchange with the right ticker. And then the report daily will pick them up. Obviously, your question shows that I should write something on the topic.
you are welcome, there is still a lot to improve.
