### ISSUE TITLE
No module named 'core'

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#16]
Trying to run the bt.ipynb and get the above error

any ideas?

**Comment by ben1628** [comment]
will try to provide more details

**Comment by psemdel** [comment]
Hi, first all jupyter scripts need to be moved one folder higher to work (still haven't found a solution to that, the classic one is to integrate my tool in pip and let you install it from there). This is what I meant with MOVE_THEM_TO_ROOT_TO_USE_THEM. 

For the zoneinfo, you are right with Python 3.8  and below you need the backports, with newer Python zoneinfo works directly.

**Comment by ben1628** [comment]
Okay, I resolved the problem by doing the following

```
import sys
sys.path.append(".")

from core import strat, indicators, bt
```

and then modify the settings.py at line 145 

```
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

...

if DEBUG and DEBUG!="False":
    with open(os.path.join(BASE_DIR, 'trading_bot/etc/DJANGO_SECRET')) as f:
        SECRET_KEY = f.read().strip()
    with open(os.path.join(BASE_DIR, 'trading_bot/etc/DB_SECRET')) as f:
        DB_SECRET_KEY = f.read().strip()
    with open(os.path.join(BASE_DIR, 'trading_bot/etc/DB_USER')) as f:
        DB_USER = f.read().strip()

```

**Comment by psemdel** [comment]
The os.path.join(BASE_DIR, is a good idea indeed, I neglected this point.
However with the sys append(".") I am not able to start the jupyter scripts from a subordner, so I don't really see the change in comparison to before. Maybe I misunderstand your actions.

**Comment by ben1628** [comment]
may be try it with two dots like this

```
import sys
sys.path.append("..")

from core import strat, indicators, bt
```
It did worked for me.

**Comment by psemdel** [comment]
It made my day, many thx!

**Comment by ben1628** [comment]
Many thanks to you, you're a great help for me! :)
