### ISSUE TITLE
version for vectorbt

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#2]
Do you have the branch for VectorBT available? Even a beta version will give me a head start.

Thanks.

**Comment by psemdel** [comment]
Hi, as it was not needed in issue #1, I did not start. But I can invest some time in it until end of year.

**Comment by ben1628** [comment]
Well, I hope you can work on that a bit,

**Comment by ben1628** [comment]
Not worth the effort, will get the pro version
