### ISSUE TITLE
101 formulaic alphas 

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#20]
What is your experiences on that?

Are you using all of that in your preselection and choose the top 10?

**Comment by psemdel** [comment]
I recommend using them only if you have very low fees, as most of them are very dynamic. You don't need to make a top 10, each alpha will give you candidates. Of course, you can imagine another algorithm, but it is not the way it is meant. You should make some backstagging (wq.ipynb), to see which one fits the best with the products you want to trade.

**Comment by ben1628** [comment]
Do you mean IB's fee is not low enough?

**Comment by psemdel** [comment]
It depends on which stock exchange you trade. On Nasdaq and NYSE, it should be ok, but it impacts much more the performance on strategies, like those alphas, with one order a day than on strategy with one order a month. I am not financial consultant, I try also to figure it out on my side. As said, perform some backtesting is probably the most reliable way to verify things.
