### ISSUE TITLE
Adding Plotly and dash to this app?

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#29]
What is your thought on this?

I'm using IB Gateway, so I will not have access to the TWS's candlesticks and various tools.  After we start the bot, it may not be a bad ideas to plot some candlestick on Django. There is some github stuff about Django Instant, plotly-dash-django using tag.  Even some real time display of Dataframe would be helpful as it is now just a black box to me, :)

Again, nothing urgent, may be we can start creating a Labels called Request/Enhancement to track that.

Even without that, this is going to be a lot of potential for this project.

**Comment by ben1628** [comment]
On second thought, this is not necessary as I could use TWS or other charting tools.  Do this in this app is not ideal and make the codes much more complicated than necessary

**Comment by psemdel** [comment]
vbt is also very good to plot things in jupyter. I also think it would be a bit the overkill to put that in django.
