### ISSUE TITLE
python-telegram-bot

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#37]
Using telgram_minimal.ipynb is working fine if I use python-telegram-bot 13.15, but fail if I upgrade to latest 21.3

Vectorbt Pro as it stands now will use the latest version, any idea how to fix it?

**Comment by ben1628** [comment]
just downgraded it and it works

**Comment by psemdel** [comment]
Thanks for the hint, I will make some tests when I have time.
