### ISSUE TITLE
Relation does not exist

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#40]
The above exception (relation "orders_stockex" does not exist LINE 1: ...in_index_id", "orders_stockex"."calc_report" FROM "orders_st... ^ ) was the direct cause of the following exception:
/home/benson/.vbt/lib/python3.10/site-packages/django/db/models/sql/compiler.py, line 1562, in execute_sql

**Comment by ben1628** [comment]
Have to create database first, and then use
```
python manage.py makemigrations
python manage.py migrate

```optionally we can load demo data to it

**Comment by psemdel** [comment]
Sorry, I am too slow. Yes create the database, migrate and then load the dump.
