### ISSUE TITLE
perform_orders

### ISSUE THREAD

**Issue by Fun1628** [psemdel/py-trading-bot#45]
I think I must missed something here,

Where is the codes that shows the automatic order when using IB?

Sell_order() is being called by perform_orders, but there is nothing in the codes that does the call

**Comment by psemdel** [comment]
Hi, it is all in ib.py. The call is done in place(). If it is a new order, it will be called by entry_place(). As described in https://github.com/psemdel/py-trading-bot/blob/main/docs/orders.md, there are many safety to avoid automatic order performance, if you don't want to.

**Comment by Fun1628** [comment]
Okay, found it!
It's in Daily_report, which call .resolve, which call buy_order or sell_order

**Comment by psemdel** [comment]
Euh, yes... it can seem complex. The whole code actually is "just" to make a report and perform orders.

**Comment by Fun1628** [comment]
Not a problem, I was lazy trying to use this site (Github) to  find it, but it proves complicated.  Finally, using VSCode to do a proper job.

Not complicated, just a different to approach a problem.  Thanks
