### ISSUE TITLE
@connect_ib problem

### ISSUE THREAD

**Issue by Fun1628** [psemdel/py-trading-bot#47]
What does this **@connect_ib** does?  I know it is called before the function, but it looks like the function is not called at all even after a successful connect.

In my case, during retireve_data_online, it calls retrieve_data_ib which has the @connect_id decorator, after it call ib_global["connected"] is true, which should mean IB is connected and the IBKR_gateway confirmed it is connected, but the retireve_data_ib never get called, and it  give this following message

INFO 63 IB retrieval of symbol failed, fallback on YF
AMD: Period '3y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', '10y', 'ytd', 'max']

**Comment by Fun1628** [comment]
Okay, found out what the problem is by adding

except Exception as error:

1/ Multiple arguments for it_is_index: that's due to the **used_api** being added to the function retrieve_data_ib.  The first time it's working because both it_is_index and use_api is false.  Second time use_api is true while it_is_index is false.  Remove used_api argument solve that.

2/  Unexpected 'client' keyword,  remove kwargs['client'] resolve problem

 ```
   def wrapper(*args,**kwargs):
        #kwargs['client'] = IBData.resolve_client(None)
        IBData.resolve_client(None)
        return func(*args,**kwargs)
    return wrapper
```





3/ now I got ERROR 159 IBData.__init__() got an unexpected keyword argument 'single_key'

Looks like there are multiple problem, so further troubleshoot is required.

**Comment by psemdel** [comment]
I will try to understand.
