### ISSUE TITLE
Strategy on Single action(stock)

### ISSUE THREAD

**Issue by Fun1628** [psemdel/py-trading-bot#49]
As suggested in Strategies.md under doc, I select Apple, which I owned and it showed on db I did have shares there, under Normal Strategy. However, I don't see any strategy being performed on Apple.

In reporting/models.py

```
                #clean the symbols
                actions=filter_intro_action(actions,_settings["DAILY_REPORT_PERIOD"])
                ##Perform a single strategy on predefined actions
                print ("daily report, doing single strategy")
                #Uses afterward as source for the data to avoid loading them several times
                ust_hold=self.init_ust(actions, exchange,it_is_index=it_is_index, **kwargs)

```
Although the comment is suggesting it is perform a single strategy, actions is getting all stocks from the exchange, not just single stock and single strategy, it seems it is doing PreSelect.

Please point me to the section that does single stock, thanks!

**Comment by psemdel** [comment]
Sure. The strategies are selected at the StockExchange level principally. So here Nasdaq.
For not having the "preSelect", remove them from your list:
![image](https://github.com/user-attachments/assets/1020c735-1a72-4d88-924a-1f8bac087617)

The "basic" strategy for single stock is the "normal". So select "normal" at StockExchange level.
Then to know which stock should be traded that way, you need to go to Strat candidatess (still in the admin panel). Select Apple.

Next time you trigger the report, it will evaluate the normal strategy for Apple and not perform any preselection.

**Comment by psemdel** [comment]
If you have a suggestion how to do it better, I am happy to listen. I find it also complicated.

**Comment by ben1628** [comment]
It's fine just need to understand the workflow
