### ISSUE TITLE
Connection refused in Kombu

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#7]
When I try to start bot, I'm running in this error

1/WARNING:kombu.connection:No hostname was supplied. Reverting to default 'localhost'

2 /Getting this connection refused error, also 

 "/home/usr/trading-bot/trading-bot/.vbt/lib/python3.10/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: [Errno 111] Connection refused

I'm new to Redis, so not sure how I can fix this.

**Comment by psemdel** [comment]
Never got this one. Normally a Redis server is started by the script. It should be started before the celery worker. The Celery logic is in trading_bot/celery.py but it is only standard code from the documentation. in trading_bot/settings.py the url is provided REDIS_URL , maybe check that its value seems ok.

**Comment by ben1628** [comment]
it's working now.  Need to make sure telegram bot is working.

**Comment by psemdel** [comment]
What did you change?

**Comment by ben1628** [comment]
I was taking a baby step to the whole process.  First, I created a django project from scratch, making sure I can see the website working, then copy py-trading-bot over and made and necessary changes.  Everything was working.

Then I started doing Redis, and telegram and ran into this error.  With your help, I find out the celery.py is missing in  trading_bot.
